### ISSUE TITLE
Where is RNA edited sites from?

### ISSUE THREAD

**Issue by wangshun1121** [inab/SmartRNASeqCaller#3]
As I asked, how did you get bed files of RNA Edit positions?

**Comment by mbosio85** [comment]
Hello,
We downloaded and merged bed files  from 
  - RADAR : [http://rnaedit.com/](http://rnaedit.com/) 
  - REDI Portal [http://srv00.recas.ba.infn.it/atlas/](http://srv00.recas.ba.infn.it/atlas/)
Hope it helps
Mattia
