### ISSUE TITLE
Running smartRNASeqCaller on hg38

### ISSUE THREAD

**Issue by travelanywhere** [inab/SmartRNASeqCaller#8]
Is there a way to run it on data generated with hg38 in stead of hg19?

**Comment by mbosio85** [comment]
Hi!
There is a way which passes by building the resource files for hg38 as in  #1 
In the upcoming days I'll generate these files and add them in the resource folder but for the moment you may follow those steps.

**Comment by mbosio85** [comment]
Hello,
I added the bed files in resources/hg38 so it should be easier to apply the tool.
Cheers
Mattia
